name: 05 - Filters Activity Types v12

on: 
    pull_request:
        types:
            - closed
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR details
              run: echo " Running whenever a PR is closed, AND base is main"