name: 06-context - Contexts

run-name: My custom workflow run - ${{ runner.os }}

on:
  push:
  workflow_dispatch:

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Sha: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Ref: ${{ github.ref }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"

            - name: Retrieve Variable
              run: |
                echo "Variable value: ${{ vars.MY_VAR }}"