name: 06-context - Contexts

run-name: 06 - contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
        debug:
            type: boolean
            default: false
env: 
  MY_WORKFLOW_VAR: "Workflow"
  MY_OVERWRITTEN_VAR: "Overwritten by workflow"
jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: "Job"
            MY_OVERWRITTEN_JOB_VAR: "Overwritten by job"
        steps:
            - name: Display Information
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Sha: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Ref: ${{ github.ref }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"

            - name: Retrieve Variable
              run: |
                echo "Variable value: ${{ vars.MY_VAR }}"

            - name: Print Env Variables
              env: 
                MY_OVERWRITTEN_VAR: "Overwritten by step"
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"